/* Generated by Yosys 0.45+139 (git sha1 8e1e2b9a3, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

(* top =  1  *)
(* src = "D:/Progamming/Verilog/fullAdder_HA/fullAdder_HA.srcs/sources_1/new/full_adder.v:23.1-33.10" *)
module full_adder(a, b, cin, sum, carry);
  (* src = "D:/Progamming/Verilog/fullAdder_HA/fullAdder_HA.srcs/sources_1/new/full_adder.v:24.11-24.12" *)
  input a;
  wire a;
  (* src = "D:/Progamming/Verilog/fullAdder_HA/fullAdder_HA.srcs/sources_1/new/full_adder.v:24.13-24.14" *)
  input b;
  wire b;
  (* src = "D:/Progamming/Verilog/fullAdder_HA/fullAdder_HA.srcs/sources_1/new/full_adder.v:28.13-28.15" *)
  wire c1;
  (* src = "D:/Progamming/Verilog/fullAdder_HA/fullAdder_HA.srcs/sources_1/new/full_adder.v:28.16-28.18" *)
  wire c2;
  (* src = "D:/Progamming/Verilog/fullAdder_HA/fullAdder_HA.srcs/sources_1/new/full_adder.v:25.16-25.21" *)
  output carry;
  wire carry;
  (* src = "D:/Progamming/Verilog/fullAdder_HA/fullAdder_HA.srcs/sources_1/new/full_adder.v:24.15-24.18" *)
  input cin;
  wire cin;
  (* src = "D:/Progamming/Verilog/fullAdder_HA/fullAdder_HA.srcs/sources_1/new/full_adder.v:28.10-28.12" *)
  wire s1;
  (* src = "D:/Progamming/Verilog/fullAdder_HA/fullAdder_HA.srcs/sources_1/new/full_adder.v:25.12-25.15" *)
  output sum;
  wire sum;
  assign carry = c2 | c1;
  (* module_not_derived = 32'd1 *)
  (* src = "D:/Progamming/Verilog/fullAdder_HA/fullAdder_HA.srcs/sources_1/new/full_adder.v:30.16-30.30" *)
  half_adder HA1 (
    .a(a),
    .b(b),
    .c(c1),
    .s(s1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "D:/Progamming/Verilog/fullAdder_HA/fullAdder_HA.srcs/sources_1/new/full_adder.v:31.16-31.34" *)
  half_adder HA2 (
    .a(s1),
    .b(cin),
    .c(c2),
    .s(sum)
  );
endmodule

(* src = "D:/Progamming/Verilog/fullAdder_HA/fullAdder_HA.srcs/sources_1/new/half_adder.v:23.1-31.10" *)
module half_adder(a, b, s, c);
  (* src = "D:/Progamming/Verilog/fullAdder_HA/fullAdder_HA.srcs/sources_1/new/half_adder.v:24.11-24.12" *)
  input a;
  wire a;
  (* src = "D:/Progamming/Verilog/fullAdder_HA/fullAdder_HA.srcs/sources_1/new/half_adder.v:24.13-24.14" *)
  input b;
  wire b;
  (* src = "D:/Progamming/Verilog/fullAdder_HA/fullAdder_HA.srcs/sources_1/new/half_adder.v:26.12-26.13" *)
  output c;
  wire c;
  (* src = "D:/Progamming/Verilog/fullAdder_HA/fullAdder_HA.srcs/sources_1/new/half_adder.v:25.12-25.13" *)
  output s;
  wire s;
  assign s = b ^ a;
  assign c = b & a;
endmodule
