/* Generated by Yosys 0.45+139 (git sha1 8e1e2b9a3, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

(* top =  1  *)
(* src = "D:/Progamming/Verilog/fullAdder/fullAdder.srcs/sources_1/new/full_adder_optimized.v:23.1-31.10" *)
module full_adder_optimized(a, b, cin, sum, cout);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "D:/Progamming/Verilog/fullAdder/fullAdder.srcs/sources_1/new/full_adder_optimized.v:24.11-24.12" *)
  input a;
  wire a;
  (* src = "D:/Progamming/Verilog/fullAdder/fullAdder.srcs/sources_1/new/full_adder_optimized.v:24.14-24.15" *)
  input b;
  wire b;
  (* src = "D:/Progamming/Verilog/fullAdder/fullAdder.srcs/sources_1/new/full_adder_optimized.v:24.17-24.20" *)
  input cin;
  wire cin;
  (* src = "D:/Progamming/Verilog/fullAdder/fullAdder.srcs/sources_1/new/full_adder_optimized.v:25.17-25.21" *)
  output cout;
  wire cout;
  (* src = "D:/Progamming/Verilog/fullAdder/fullAdder.srcs/sources_1/new/full_adder_optimized.v:25.12-25.15" *)
  output sum;
  wire sum;
  assign _0_ = ~(b ^ a);
  assign sum = ~(_0_ ^ cin);
  assign _1_ = ~(b & a);
  assign _2_ = cin & ~(_0_);
  assign cout = _2_ | ~(_1_);
endmodule
